name = "wanz-ai"
main = "api/worker.js"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "KV_USERS"
id = "4ec4c33a20b24ffaac8f95c5b2a3e946"

[[kv_namespaces]]
binding = "KV_USAGE"
id = "659aa018b8f1476da06baa7486b13779"

[ai]
binding = "AI"
